trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Azure Container Registry'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Run services'
      detached: false

